#include "images.h"

const ext_img_desc_t images[22] = {
    { "splash", &img_splash },
    { "arclock", &img_arclock },
    { "battery", &img_battery },
    { "battery charging", &img_battery_charging },
    { "33 connection", &img_33_connection },
    { "66 connection", &img_66_connection },
    { "100 connection", &img_100_connection },
    { "connection_0", &img_connection_0 },
    { "arcunlock", &img_arcunlock },
    { "arrow", &img_arrow },
    { "config", &img_config },
    { "skateboard", &img_skateboard },
    { "info", &img_info },
    { "about", &img_about },
    { "light_yellow", &img_light_yellow },
    { "light_white", &img_light_white },
    { "toggle_on", &img_toggle_on },
    { "toggle_off", &img_toggle_off },
    { "hand_sensor", &img_hand_sensor },
    { "throttle", &img_throttle },
    { "odometer", &img_odometer },
    { "warning", &img_warning },
};
