#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "ble_spp_client.h"
#include "throttle.h"
#include "lcd.h"
#include "driver/gpio.h"
#include "power.h"
#include "button.h"
#include "ui/ui.h"  // Generated by SquareLine Studio
#include "vesc_config.h"
#include "battery.h"
#include "esp_heap_caps.h"
#include "ui_updater.h"
#include "esp_timer.h"
#include "usb_serial_handler.h"
#include "level_assistant.h"
#include "version.h"

#define TAG "MAIN"

#define TELEMETRY_LOG_INTERVAL_MS 1000  // Log every 1 second

extern bool is_connect;

static void splash_timer_cb(lv_timer_t * timer)
{
    lv_disp_load_scr(objects.home_screen);  // Switch to home screen after timeout
}

static void telemetry_log_task(void *pvParameters)
{
    TickType_t last_wake_time = xTaskGetTickCount();
    const TickType_t frequency = pdMS_TO_TICKS(TELEMETRY_LOG_INTERVAL_MS);

    while (1) {
        vTaskDelayUntil(&last_wake_time, frequency);

        // Read throttle value
        int32_t throttle_value = throttle_read_value();

        // Read brake value
        int32_t brake_value = brake_read_value();

        uint32_t ble_value = get_throttle_brake_ble_value();

        // Log all values
        ESP_LOGI(TAG, "Throttle: %ld, Brake: %ld, BLE Value: %ld", throttle_value, brake_value, ble_value);
    }
}

void app_main(void)
{
    // Set GPIO 4 to HIGH as first action
    gpio_config_t gpio4_conf = {
        .pin_bit_mask = (1ULL << GPIO_NUM_4),
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE
    };
    ESP_ERROR_CHECK(gpio_config(&gpio4_conf));
    ESP_ERROR_CHECK(gpio_set_level(GPIO_NUM_4, 1));

    ESP_LOGI(TAG, "Starting Application");

    ESP_LOGI(TAG, "Firmware version: %s", APP_VERSION_STRING);
    ESP_LOGI(TAG, "Build date: %s %s", BUILD_DATE, BUILD_TIME);
    ESP_LOGI(TAG, "Target: %s", CONFIG_IDF_TARGET);
    ESP_LOGI(TAG, "IDF version: %s", esp_get_idf_version());

    // Initialize power module
    power_init();

    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    // Initialize VESC configuration
    ESP_ERROR_CHECK(vesc_config_init());

    // Initialize level assistant
    ESP_ERROR_CHECK(level_assistant_init());

    // Initialize ADC and start tasks
    ESP_ERROR_CHECK(adc_init());
    adc_start_task();

    // Wait for ADC calibration
    while (!throttle_is_calibrated()) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    // Initialize USB Serial Handler FIRST (before BLE UART setup)
    // Note: This is optional - if it fails, the device will still work without USB commands
    ESP_LOGI(TAG, "Attempting to initialize USB Serial Handler...");

    // Initialize full USB serial handler
    usb_serial_init();
    usb_serial_start_task();

    // Initialize BLE
    spp_client_demo_init();
    ESP_LOGI(TAG, "BLE Initialization complete");

    // Add heap info logging
    ESP_LOGI(TAG, "Free heap after BLE init: %lu", esp_get_free_heap_size());

    // Initialize LCD and LVGL
    lcd_init();

    ESP_ERROR_CHECK(battery_init());
    battery_start_monitoring();

    // Start power monitoring
    power_start_monitoring();

    // Initialize SquareLine Studio UI
    ui_init();

    // Set initial speed unit from saved configuration
    vesc_config_t config;
    esp_err_t err = vesc_config_load(&config);
    if (err == ESP_OK) {
        ui_update_speed_unit(config.speed_unit_mph);
        ESP_LOGI(TAG, "Initial speed unit set to: %s", config.speed_unit_mph ? "mi/h" : "km/h");
    } else {
        ESP_LOGW(TAG, "Failed to load speed unit configuration, using default km/h");
        ui_update_speed_unit(false); // Default to km/h
    }

    lv_disp_load_scr(objects.splash_screen);  // Load splash screen first
    lv_timer_t * splash_timer = lv_timer_create(splash_timer_cb, 3000, NULL);  // Create timer for 3 seconds
    lv_timer_set_repeat_count(splash_timer, 1);  // Run only once

    // Create telemetry logging task
    xTaskCreate(telemetry_log_task, "telemetry_log", 4096, NULL, 1, NULL);

    // Main task loop
    while (1) {
        power_check_inactivity(is_connect);

        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

