#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "ble_spp_client.h"
#include "adc.h"
#include "lcd.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "sleep.h"
#include "button.h"
#include "ui/ui.h"  // Generated by SquareLine Studio
#include "vesc_config.h"
#include "battery.h"
#include "esp_heap_caps.h"
#include "ui_updater.h"
#include "esp_timer.h"
#include "usb_serial_handler.h"
#include "level_assistant.h"
#include "version.h"

#define TAG "MAIN"


extern bool is_connect;

static void splash_timer_cb(lv_timer_t * timer)
{
    lv_disp_load_scr(objects.home_screen);  // Switch to home screen after timeout
}

/*static void print_telemetry_task(void *pvParameters)
{
    while (1) {
        if (is_connect) {
            // Print VESC Data
            ESP_LOGI(TAG, "-------- VESC Data --------");
            ESP_LOGI(TAG, "Temperatures:");
            ESP_LOGI(TAG, "  MOSFET: %.1f°C", get_latest_temp_mos());
            ESP_LOGI(TAG, "  Motor:  %.1f°C", get_latest_temp_motor());
            ESP_LOGI(TAG, "Current:");
            ESP_LOGI(TAG, "  Motor:  %.1fA", get_latest_current_motor());
            ESP_LOGI(TAG, "  Input:  %.1fA", get_latest_current_in());
            ESP_LOGI(TAG, "Motor:");
            ESP_LOGI(TAG, "  RPM:    %ld", get_latest_erpm());
            ESP_LOGI(TAG, "  Speed:  %.1f km/h", get_latest_erpm() / 7.0f);
            ESP_LOGI(TAG, "Battery:");
            ESP_LOGI(TAG, "  Voltage: %.1fV", get_latest_voltage());
            ESP_LOGI(TAG, "-------------------------\n");

            // Print BMS Data
            ESP_LOGI(TAG, "--------- BMS Data ---------");
            ESP_LOGI(TAG, "Pack:");
            ESP_LOGI(TAG, "  Voltage:   %.2fV", get_bms_total_voltage());
            ESP_LOGI(TAG, "  Current:   %.2fA", get_bms_current());
            ESP_LOGI(TAG, "Capacity:");
            ESP_LOGI(TAG, "  Remaining: %.2fAh", get_bms_remaining_capacity());
            ESP_LOGI(TAG, "  Nominal:   %.2fAh", get_bms_nominal_capacity());
            ESP_LOGI(TAG, "  Percent:   %.1f%%",
                    (get_bms_remaining_capacity() / get_bms_nominal_capacity()) * 100.0f);

            uint8_t num_cells = get_bms_num_cells();
            ESP_LOGI(TAG, "Cells (%d):", num_cells);

            // Print cell voltages in a grid format
            for (int i = 0; i < num_cells; i++) {
                if (i % 4 == 0) {
                    ESP_LOGI(TAG, "  ");
                }
                ESP_LOGI(TAG, "Cell %2d: %.3fV  ", i+1, get_bms_cell_voltage(i));
            }
            ESP_LOGI(TAG, "--------------------------\n");
        }
        vTaskDelay(pdMS_TO_TICKS(1000)); // Print every second
    }
}*/

void app_main(void)
{
    // Set GPIO 4 to HIGH as first action
    gpio_config_t gpio4_conf = {
        .pin_bit_mask = (1ULL << GPIO_NUM_4),
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE
    };
    ESP_ERROR_CHECK(gpio_config(&gpio4_conf));
    ESP_ERROR_CHECK(gpio_set_level(GPIO_NUM_4, 1));

    ESP_LOGI(TAG, "Starting Application");

    ESP_LOGI(TAG, "Firmware version: %s", APP_VERSION_STRING);
    ESP_LOGI(TAG, "Build date: %s %s", BUILD_DATE, BUILD_TIME);
    ESP_LOGI(TAG, "Target: %s", CONFIG_IDF_TARGET);
    ESP_LOGI(TAG, "IDF version: %s", esp_get_idf_version());

    // Initialize sleep module
    sleep_init();

    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    // Initialize VESC configuration
    ESP_ERROR_CHECK(vesc_config_init());

    // Initialize level assistant
    ESP_ERROR_CHECK(level_assistant_init());

    // Initialize ADC and start tasks
    ESP_ERROR_CHECK(adc_init());
    adc_start_task();

    // Wait for ADC calibration
    while (!adc_is_calibrated()) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    // Initialize USB Serial Handler FIRST (before BLE UART setup)
    // Note: This is optional - if it fails, the device will still work without USB commands
    ESP_LOGI(TAG, "Attempting to initialize USB Serial Handler...");

    // Initialize full USB serial handler
    usb_serial_init();
    usb_serial_start_task();

    // Initialize BLE
    spp_client_demo_init();
    ESP_LOGI(TAG, "BLE Initialization complete");

    // Add heap info logging
    ESP_LOGI(TAG, "Free heap after BLE init: %lu", esp_get_free_heap_size());

    // Initialize LCD and LVGL
    lcd_init();

    ESP_ERROR_CHECK(battery_init());
    battery_start_monitoring();

    // Start sleep monitoring
    sleep_start_monitoring();

    // Initialize SquareLine Studio UI
    ui_init();

    // Set initial speed unit from saved configuration
    vesc_config_t config;
    esp_err_t err = vesc_config_load(&config);
    if (err == ESP_OK) {
        ui_update_speed_unit(config.speed_unit_mph);
        ESP_LOGI(TAG, "Initial speed unit set to: %s", config.speed_unit_mph ? "mi/h" : "km/h");
    } else {
        ESP_LOGW(TAG, "Failed to load speed unit configuration, using default km/h");
        ui_update_speed_unit(false); // Default to km/h
    }

    lv_disp_load_scr(objects.splash_screen);  // Load splash screen first
    lv_timer_t * splash_timer = lv_timer_create(splash_timer_cb, 3000, NULL);  // Create timer for 3 seconds
    lv_timer_set_repeat_count(splash_timer, 1);  // Run only once

    // Create telemetry printing task
    //xTaskCreate(print_telemetry_task, "telemetry", 4096, NULL, 1, NULL);

    // Main task can now sleep
    while (1) {
        sleep_check_inactivity(is_connect);

        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

